name: null
favicon: null
layout_spectrum: 0.77334
typography_spectrum: 0.37409
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#2285b0'
    - '#343434'
    - '#eaad98'
    - '#8dc9cb'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: 45457d1d-074d-46bb-839b-e2e4b4b96b55
    url: tatoo
